#!/bin/bash

# Readline library configuration options
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Disable beeping and window flashing
set bell-style none

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Auto list TAB completions
set show-all-if-ambiguous off

# Auto complete last iniated command (like git clone ... upkey and complete with last git clone command)
"\e[A": history-search-backward
"\e[B": history-search-forward
